name: _error
timestamp: 1563527833
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1563527832
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-4811: Logo
  spacer:
    spacer-8386: Spacer
    spacer-3945: Spacer
  menu:
    menu-9917: Menu
  content:
    system-content-5996: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-9659: Copyright
  branding:
    branding-3378: Branding
  mobile-menu:
    mobile-menu-9890: Mobile-menu
inherit: {  }
