version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1563527832
layout:
  /header/:
    -
      - 'logo-8489 30'
      - 'spacer-2421 70'
  /main/:
    -
      - system-messages-4084
    -
      - system-content-8912
  /footer/:
    -
      - position-footer
    -
      - 'copyright-9491 40'
      - 'spacer-1483 30'
      - 'branding-7552 30'
structure:
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
