name: 23
timestamp: 1584945590
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1563522857
positions:
  aside: Aside
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  content:
    system-content-4006: 'Page Content'
  messages:
    system-messages-4226: 'System Messages'
  logo:
    logo-2860: 'Logo / Image'
    logo-6277: 'Logo / Image'
  menu:
    menu-1489: Menu
  custom:
    custom-7752: Social
    custom-1261: 'Logo And Descrıptıon'
    custom-4549: 'Footer Menu'
    custom-9512: Contact
    custom-4508: 'Copyright and Policies'
  spacer:
    spacer-9842: Spacer
    spacer-8779: Spacer
  mobile-menu:
    mobile-menu-7663: Mobile-menu
  position:
    position-position-1453: Aside
    position-position-6572: Sidebar
inherit:
  9:
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    system-messages-4226: system-messages-8776
    logo-2860: logo-9531
    menu-1489: menu-4597
    custom-7752: custom-2297
    custom-1261: custom-7183
    spacer-9842: spacer-5222
    custom-4549: custom-3360
    spacer-8779: spacer-4416
    custom-9512: custom-7504
    custom-4508: custom-3748
    logo-6277: logo-9504
    mobile-menu-7663: mobile-menu-9030
  17:
    header: header
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    sidebar: sidebar
    position-position-1453: position-position-4734
    position-position-6572: position-position-3949
