ordering:
  home-rus: ''
  язык:
    словарь: ''
    образование:
      грамматика: ''
      произношение: ''
      лексика: ''
  история:
    древние_тюрки: ''
    золотая_орда: ''
    крымское_ханство: ''
    послеханский_период: ''
    советский_период: ''
    xxi_век: ''
  __module-Y4gF9: ''
  вход-регистрация: ''
  выйти: ''
  свяжитесь_с_нами: ''
items:
  home-rus:
    id: 110
  язык:
    id: 120
  язык/словарь:
    id: 112
  язык/образование:
    id: 121
  язык/образование/грамматика:
    id: 123
  язык/образование/произношение:
    id: 125
  язык/образование/лексика:
    id: 126
  история:
    id: 134
  история/древние_тюрки:
    id: 135
  история/золотая_орда:
    id: 136
  история/крымское_ханство:
    id: 137
  история/послеханский_период:
    id: 138
  история/советский_период:
    id: 139
  история/xxi_век:
    id: 140
  вход-регистрация:
    id: 182
  выйти:
    id: 183
  свяжитесь_с_нами:
    id: 186
  __module-Y4gF9:
    type: particle
    particle: module
    title: 'Change language'
    options:
      particle:
        enabled: '1'
        module_id: '95'
        chrome: ''
      block:
        class: home-lang-switcher
        extra: {  }
    enabled: '1'
