ordering:
  home-english: ''
  lang:
    dictionary:
      edit-dictionary: ''
    education:
      grammar: ''
      pronunciation: ''
      lexicon: ''
  history:
    ancient_turks: ''
    golden_horde: ''
    crimean_khanate: ''
    postkhan_period: ''
    soviet_period: ''
    xxi_century: ''
  culture:
    traditions: ''
    lifestyle: ''
    music: ''
    literature: ''
    art: ''
    religion: ''
  books:
    educational_literature: ''
    historical_literature: ''
    culture_literature: ''
    for_children: ''
    fiction: ''
    biographies: ''
  other:
    discussions: ''
    downloads: ''
    gallery: ''
    partners: ''
    about_us: ''
  __module-7yXP8: ''
  login-register: ''
  logout: ''
  contact_us: ''
  terms_of_use: ''
  privacy_policy: ''
items:
  home-english:
    id: 109
  lang:
    id: 113
  lang/dictionary:
    id: 111
    dropdown_dir: right
    dropdown_hide: '1'
    width: auto
  lang/dictionary/edit-dictionary:
    id: 205
  lang/education:
    id: 115
  lang/education/grammar:
    id: 117
  lang/education/pronunciation:
    id: 118
  lang/education/lexicon:
    id: 119
  history:
    id: 127
  history/ancient_turks:
    id: 128
  history/golden_horde:
    id: 129
  history/crimean_khanate:
    id: 130
  history/postkhan_period:
    id: 131
  history/soviet_period:
    id: 132
  history/xxi_century:
    id: 133
  culture:
    id: 141
  culture/traditions:
    id: 142
  culture/lifestyle:
    id: 143
  culture/music:
    id: 144
  culture/literature:
    id: 145
  culture/art:
    id: 146
  culture/religion:
    id: 147
  books:
    id: 159
  books/educational_literature:
    id: 160
  books/historical_literature:
    id: 161
  books/culture_literature:
    id: 162
  books/for_children:
    id: 163
  books/fiction:
    id: 164
  books/biographies:
    id: 165
  other:
    id: 174
  other/discussions:
    id: 155
  other/downloads:
    id: 176
  other/gallery:
    id: 157
  other/partners:
    id: 177
  other/about_us:
    id: 200
  login-register:
    id: 180
  logout:
    id: 184
  contact_us:
    id: 185
  terms_of_use:
    id: 201
  privacy_policy:
    id: 202
  __module-7yXP8:
    type: particle
    particle: module
    title: 'Change language'
    options:
      particle:
        enabled: '1'
        module_id: '95'
        chrome: ''
      block:
        class: home-lang-switcher
        extra: {  }
    enabled: true
    anchor_class: ''
