ordering:
  home-rus: ''
  язык:
    словарь:
      редактировать-словарь: ''
    образование:
      грамматика: ''
      произношение: ''
      лексика: ''
      добавление-урока: ''
  история:
    древние_тюрки: ''
    золотая_орда: ''
    крымское_ханство: ''
    послеханский_период: ''
    советский_период: ''
    xxi_век: ''
  культура:
    традиции: ''
    быт: ''
    музыка: ''
    литература: ''
    живопись: ''
    религия: ''
  книги:
    учебная_литература: ''
    историческая_литература: ''
    книги_о_культуре: ''
    детская_литература: ''
    худодественная_литература: ''
    биографии: ''
  прочее:
    загрузки: ''
    партнеры: ''
    галерея: ''
    обсуждения: ''
    о_нас: ''
  __module-Y4gF9: ''
  вход-регистрация: ''
  выйти: ''
  свяжитесь_с_нами: ''
  политика_конфиденциальности: ''
  пользовательское_соглашение: ''
  мой-профиль:
    редактировать-профиль: ''
    обо-мне: ''
    создать-урок: ''
items:
  мой-профиль:
    id: 208
  мой-профиль/редактировать-профиль:
    id: 210
  мой-профиль/обо-мне:
    id: 209
  мой-профиль/создать-урок:
    id: 211
  home-rus:
    id: 110
  язык:
    id: 120
  язык/словарь:
    id: 112
    dropdown_dir: right
    dropdown_hide: '1'
    width: auto
  язык/словарь/редактировать-словарь:
    id: 206
  язык/образование:
    id: 121
  язык/образование/грамматика:
    id: 123
  язык/образование/произношение:
    id: 125
  язык/образование/лексика:
    id: 126
  язык/образование/добавление-урока:
    id: 207
  история:
    id: 134
  история/древние_тюрки:
    id: 135
  история/золотая_орда:
    id: 136
  история/крымское_ханство:
    id: 137
  история/послеханский_период:
    id: 138
  история/советский_период:
    id: 139
  история/xxi_век:
    id: 140
  культура:
    id: 148
  культура/традиции:
    id: 149
  культура/быт:
    id: 150
  культура/музыка:
    id: 151
  культура/литература:
    id: 152
  культура/живопись:
    id: 153
  культура/религия:
    id: 154
  книги:
    id: 166
  книги/учебная_литература:
    id: 167
  книги/историческая_литература:
    id: 168
  книги/книги_о_культуре:
    id: 169
  книги/детская_литература:
    id: 170
  книги/худодественная_литература:
    id: 172
  книги/биографии:
    id: 173
  прочее:
    id: 175
  прочее/загрузки:
    id: 178
  прочее/партнеры:
    id: 179
  прочее/галерея:
    id: 158
  прочее/обсуждения:
    id: 156
  прочее/о_нас:
    id: 199
  вход-регистрация:
    id: 182
  выйти:
    id: 183
  свяжитесь_с_нами:
    id: 186
  политика_конфиденциальности:
    id: 203
  пользовательское_соглашение:
    id: 204
  __module-Y4gF9:
    type: particle
    particle: module
    title: 'Change language'
    options:
      particle:
        enabled: '1'
        module_id: '95'
        chrome: ''
      block:
        class: home-lang-switcher
        extra: {  }
    enabled: true
    anchor_class: ''
