ordering:
  home: ''
  __module-H7nZF: ''
  feeds: ''
items:
  home:
    id: 101
  feeds:
    id: 107
  __module-H7nZF:
    type: particle
    particle: module
    title: 'Gantry 5 Particle'
    options:
      particle:
        enabled: '1'
        module_id: '90'
        chrome: ''
      block:
        class: mod-languages
        extra: {  }
    enabled: '1'
