preset: preset1
accent:
  color-1: '#66ad4c'
  color-2: '#66ad4c'
link:
  regular: '#66ad4c'
navigation:
  background: '#424753'
header:
  background-image: 'gantry-media://header/crimean-1.jpg'
  background-overlay: disabled
