version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1563522857
layout:
  navigation: {  }
  /header/: {  }
  /intro/:
    -
      - position-module-2671
  /features/: {  }
  /utility/: {  }
  /above/: {  }
  /testimonials/: {  }
  /expanded/: {  }
  /container-main/:
    -
      -
        'aside 25': {  }
      -
        'mainbar 50': {  }
      -
        'sidebar 25': {  }
  footer: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    inherit:
      outline: '14'
      include:
        - attributes
        - children
  header:
    attributes:
      boxed: ''
      class: ''
      variations: ''
  intro:
    type: section
    attributes:
      boxed: ''
      class: lugat-container
      variations: ''
  features:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  above:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  expanded:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  aside:
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
    block:
      fixed: '1'
  mainbar:
    type: section
    subtype: main
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  sidebar:
    type: section
    subtype: aside
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
      class: ''
      extra: {  }
  footer:
    inherit:
      outline: '14'
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: '14'
      include:
        - attributes
        - children
content:
  position-module-2671:
    title: 'Module Instance'
    attributes:
      module_id: '93'
      key: module-instance
