name: 17
timestamp: 1569347617
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1563522857
positions:
  aside: Aside
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  module:
    position-module-2635: 'Module Instance'
    position-module-5220: 'Module Instance'
  position:
    position-position-4734: Aside
    position-position-3949: Sidebar
  content:
    system-content-1587: 'Page Content'
  messages:
    system-messages-7444: 'System Messages'
  logo:
    logo-2290: 'Logo / Image'
    logo-5017: 'Logo / Image'
  menu:
    menu-9312: Menu
  social:
    social-9457: Social
  custom:
    custom-9538: 'Custom HTML'
  horizontalmenu:
    horizontalmenu-5881: 'Horizontal Menu'
  totop:
    totop-5261: 'To Top'
  mobile-menu:
    mobile-menu-2777: Mobile-menu
inherit:
  9:
    navigation: navigation
    footer: footer
    system-messages-7444: system-messages-8776
    logo-2290: logo-9531
    menu-9312: menu-4597
    social-9457: social-6902
    position-module-5220: position-module-5240
    logo-5017: logo-1144
    custom-9538: custom-3748
    horizontalmenu-5881: horizontalmenu-5487
    totop-5261: totop-3746
  default:
    offcanvas: offcanvas
    mobile-menu-2777: mobile-menu-9030
