version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1563522857
layout:
  /navigation/:
    -
      - system-messages-1962
    -
      - 'logo-5571 22'
      - 'menu-6097 46'
      - 'position-module-6835 16'
      - 'menu-6935 16'
  /header/:
    -
      - owlcarousel-1772
    -
      - custom-6019
  intro: {  }
  features: {  }
  utility: {  }
  above: {  }
  testimonials: {  }
  expanded: {  }
  /container-main/:
    -
      -
        'aside 25': {  }
      -
        'mainbar 50': {  }
      -
        'sidebar 25': {  }
  /footer/:
    -
      - 'logo-1144 16'
      - 'custom-3748 25'
      - 'horizontalmenu-5487 41'
      - 'totop-3746 18'
  offcanvas: {  }
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
      class: diyar-main-navigation
      variations: ''
  header:
    attributes:
      boxed: ''
      class: diyar-main-header
      variations: ''
  intro:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  features:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  utility:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  above:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  testimonials:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  expanded:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  aside:
    inherit:
      outline: '9'
      include:
        - attributes
        - block
        - children
    block:
      fixed: '1'
  mainbar:
    type: section
    subtype: main
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  sidebar:
    type: section
    subtype: aside
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
      class: ''
      variations: ''
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
content:
  system-messages-1962:
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: system-messages-4409
  logo-5571:
    title: 'Logo / Image'
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: logo-8554
  menu-6097:
    attributes:
      menu: enter-russianmenu
  position-module-6835:
    title: 'Module Instance'
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: position-module-5422
  menu-6935:
    attributes:
      menu: russian-user-menu
  owlcarousel-1772:
    title: 'Header Carousel'
    inherit:
      outline: default
      particle: owlcarousel-5369
      include:
        - attributes
  custom-6019:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"benefit-content revealOnScroll\" data-animation=\"fadeIn\" data-timeout=\"100\">\n        <h1>Русская страница</h1>\n<p>When we started the Gantry 5 project, we wanted to think past the concept of Gantry as a framework.</p>\n<p>We wanted to create something so <strong>versatile</strong> and <strong>powerful</strong>, that it could stand on its own as a platform, virtually independent of a CMS in concept and implementation.</p>\n</div>"
  logo-1144:
    title: 'Logo / Image'
    inherit:
      outline: default
      particle: logo-8554
      include:
        - attributes
        - block
  custom-3748:
    title: 'Custom HTML'
    attributes:
      html: '<p>Разработано командой Diyar совместно с Adam Hider</p>'
  horizontalmenu-5487:
    title: 'Horizontal Menu'
    attributes:
      items:
        -
          text: Словарь
          link: 'http://localhost:888/joomla/index.php/dictionary-rus'
          name: Dictionary
  totop-3746:
    title: 'To Top'
    attributes:
      icon: 'fa fa-chevron-up fa-fw'
      content: Наверх
