preset: preset3
base:
  background: '#ffffff'
  text-color: '#424753'
accent:
  color-1: '#5dad45'
  color-2: '#37536a'
font:
  family-default: 'family=Open+Sans:300,700,400'
  family-title: 'family=Open+Sans:300,700,400'
link:
  regular: '#5dad45'
  hover: '#424753'
header:
  background: '#312f38'
features:
  background: '#ffffff'
utility:
  background: '#37536a'
testimonials:
  background: '#5dad45'
footer:
  background: '#312f38'
