name: '9'
timestamp: 1570643471
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1563522857
positions:
  aside: Aside
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-8776: 'System Messages'
  logo:
    logo-9531: 'Logo / Image'
    logo-1144: 'Logo / Image'
  menu:
    menu-4597: Menu
    menu-3291: Menu
  module:
    position-module-5240: 'Module Instance'
    position-module-5886: 'Module Instance'
  owlcarousel:
    owlcarousel-8554: 'Header Carousel'
  custom:
    custom-7115: 'Custom HTML'
    custom-4443: Features
    custom-8257: 'Customer Testimonials'
    custom-8076: 'Develop CMS themes quickly'
    custom-7874: 'Social Share'
    custom-3748: 'Custom HTML'
  contenttabs:
    contenttabs-2815: 'Content Tabs'
  contentcubes:
    contentcubes-7483: 'Content Cubes'
  position:
    position-position-4734: Aside
  horizontalmenu:
    horizontalmenu-5487: 'Horizontal Menu'
  totop:
    totop-3746: 'To Top'
  mobile-menu:
    mobile-menu-4518: Mobile-menu
inherit:
  default:
    system-messages-8776: system-messages-4409
    logo-9531: logo-8554
    position-module-5240: position-module-5422
    owlcarousel-8554: owlcarousel-5369
    intro: intro
    position-module-5886: position-module-2306
    features: features
    custom-4443: custom-3119
    utility: utility
    contenttabs-2815: contenttabs-3854
    above: above
    contentcubes-7483: contentcubes-7850
    testimonials: testimonials
    custom-8257: custom-7658
    expanded: expanded
    custom-8076: custom-6355
    custom-7874: custom-6291
    mainbar: mainbar
    sidebar: sidebar
    logo-1144: logo-7150
    offcanvas: offcanvas
    mobile-menu-4518: mobile-menu-9030
