version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1563522857
layout:
  /navigation/:
    -
      - system-messages-8776
    -
      - 'logo-9531 20'
      - 'menu-4597 80'
  /header/:
    -
      - owlcarousel-8554
    -
      - custom-7115
  intro: {  }
  features: {  }
  utility: {  }
  above: {  }
  testimonials: {  }
  expanded: {  }
  /container-main/:
    -
      -
        'aside 25':
          -
            - position-position-4734
      -
        'mainbar 50': {  }
      -
        'sidebar 25': {  }
  /footer/:
    -
      - 'logo-1144 16'
      - 'custom-3748 37'
      - 'horizontalmenu-5487 29'
      - 'totop-3746 18'
  offcanvas:
    -
      - logo-9504
    -
      - mobile-menu-9030
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
      class: diyar-main-navigation
      variations: ''
  header:
    attributes:
      boxed: ''
      class: diyar-main-header
      variations: ''
  intro:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  features:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  utility:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  above:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  testimonials:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  expanded:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  aside:
    attributes:
      class: ''
    block:
      fixed: '1'
  mainbar:
    type: section
    subtype: main
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  sidebar:
    type: section
    subtype: aside
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
      class: ''
      variations: ''
  offcanvas:
    attributes:
      position: g-offcanvas-left
      class: ''
      extra: {  }
      swipe: '1'
      css3animation: '1'
content:
  system-messages-8776:
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: system-messages-4409
  logo-9531:
    title: 'Logo / Image'
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: logo-8554
  menu-4597:
    attributes:
      menu: enter-englismenu
      mobileTarget: '1'
      forceTarget: '0'
    block:
      class: home-menu
  owlcarousel-8554:
    title: 'Header Carousel'
    attributes:
      enabled: 0
      class: home-header-image
      items:
        -
          class: ''
          image: 'gantry-media://headers/1598836_original.jpg'
          title: ''
          desc: ''
          link: ''
          linktext: ''
          buttonclass: button-outline
          disable: '0'
          name: Image1
  custom-7115:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"benefit-content revealOnScroll\" data-animation=\"fadeIn\" data-timeout=\"100\">\n        <h1>Welcome!</h1>\n<p>Diyar is a modern Crimean Tatar website dedicated to the language, history and culture of Crimean Tatars. </br>\nHere we collect bit by bit everything that concerns the Crimean Tatar people: from textbooks and dictionaries to historical chronicles and autobiographies. </br>\nIf you have the opportunity to extend our collection with your materials, please contact us. Any of your contributions is very valuable to us.\n</p>\n</div>"
  position-position-4734:
    title: Aside
    attributes:
      key: aside
  logo-1144:
    title: 'Logo / Image'
    inherit:
      outline: default
      particle: logo-7150
      include:
        - attributes
        - block
  custom-3748:
    title: 'Custom HTML'
    attributes:
      enabled: 0
      html: '<p>Developed by Adam Hider and Diyar Team</p>'
  horizontalmenu-5487:
    title: 'Horizontal Menu'
    attributes:
      enabled: 0
      items:
        -
          text: Dictionary
          link: 'http://localhost:888/joomla/index.php/dictionary'
          name: Dictionary
  totop-3746:
    title: 'To Top'
  logo-9504:
    title: 'Logo / Image'
    attributes:
      image: 'gantry-media://header/SIDEBAR BACKGROUND.jpg'
      svg: ''
      class: ''
    block:
      class: offcanvas-image
