name: _body_only
timestamp: 1563527833
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1563527832
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-5472: 'System Messages'
  content:
    system-content-9188: 'Page Content'
inherit: {  }
